"""add article table

Revision ID: c078d45dfdd4
Revises: 
Create Date: 2024-12-18 21:57:20.117601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c078d45dfdd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translator_article',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the article'),
    sa.Column('title', sa.String(), nullable=False, comment='Title of the article'),
    sa.Column('text', sa.Text(), nullable=False, comment='Main content of the article'),
    sa.Column('source_language', sa.String(), nullable=False, comment='Source language of the article'),
    sa.Column('is_original', sa.Boolean(), nullable=False, comment='Flag indicating if the article is an original(True) or a translation (False)'),
    sa.Column('original_article_id', sa.UUID(), nullable=True, comment='Foreign key to the original article if thisarticle is a translation'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['original_article_id'], ['translator_article.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='A table with info about the articles'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translator_article')
    # ### end Alembic commands ###
